//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by PowerPMAC IDE.
//     Date: 2026/3/4, Time: 19:43
//     
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Slave_1001 [Diamond - E] Station Address-1001
#define Slave_1001_Diamond_E_1001_Index 0

// Inputs
#define Slave_1001_Diamond_E_1001_6041_0_Statusword pshm->ECAT[0].IO[4096].Data
#define Slave_1001_Diamond_E_1001_6064_0_Positionactualvalue pshm->ECAT[0].IO[4097].Data
#define Slave_1001_Diamond_E_1001_6077_0_Torqueactualvalue pshm->ECAT[0].IO[4098].Data
#define Slave_1001_Diamond_E_1001_6061_0_Modesofoperationdisplay pshm->ECAT[0].IO[4099].Data
#define Slave_1001_Diamond_E_1001_60FD_0_Digitalinputs pshm->ECAT[0].IO[4100].Data

// Outputs
#define Slave_1001_Diamond_E_1001_6040_0_Controlword pshm->ECAT[0].IO[0].Data
#define Slave_1001_Diamond_E_1001_607A_0_Targetposition pshm->ECAT[0].IO[1].Data
#define Slave_1001_Diamond_E_1001_6071_0_Targettorque pshm->ECAT[0].IO[2].Data
#define Slave_1001_Diamond_E_1001_6060_0_Modesofoperation pshm->ECAT[0].IO[3].Data

// Slave_1002 [Diamond - E] Station Address-1002
#define Slave_1002_Diamond_E_1002_Index 1

// Inputs
#define Slave_1002_Diamond_E_1002_6041_0_Statusword pshm->ECAT[0].IO[4101].Data
#define Slave_1002_Diamond_E_1002_6064_0_Positionactualvalue pshm->ECAT[0].IO[4102].Data
#define Slave_1002_Diamond_E_1002_6077_0_Torqueactualvalue pshm->ECAT[0].IO[4103].Data
#define Slave_1002_Diamond_E_1002_6061_0_Modesofoperationdisplay pshm->ECAT[0].IO[4104].Data
#define Slave_1002_Diamond_E_1002_60FD_0_Digitalinputs pshm->ECAT[0].IO[4105].Data

// Outputs
#define Slave_1002_Diamond_E_1002_6040_0_Controlword pshm->ECAT[0].IO[4].Data
#define Slave_1002_Diamond_E_1002_607A_0_Targetposition pshm->ECAT[0].IO[5].Data
#define Slave_1002_Diamond_E_1002_6071_0_Targettorque pshm->ECAT[0].IO[6].Data
#define Slave_1002_Diamond_E_1002_6060_0_Modesofoperation pshm->ECAT[0].IO[7].Data

// Slave_1003 [Diamond - E] Station Address-1003
#define Slave_1003_Diamond_E_1003_Index 2

// Inputs
#define Slave_1003_Diamond_E_1003_6041_0_Statusword pshm->ECAT[0].IO[4106].Data
#define Slave_1003_Diamond_E_1003_6064_0_Positionactualvalue pshm->ECAT[0].IO[4107].Data
#define Slave_1003_Diamond_E_1003_6077_0_Torqueactualvalue pshm->ECAT[0].IO[4108].Data
#define Slave_1003_Diamond_E_1003_6061_0_Modesofoperationdisplay pshm->ECAT[0].IO[4109].Data
#define Slave_1003_Diamond_E_1003_60FD_0_Digitalinputs pshm->ECAT[0].IO[4110].Data

// Outputs
#define Slave_1003_Diamond_E_1003_6040_0_Controlword pshm->ECAT[0].IO[8].Data
#define Slave_1003_Diamond_E_1003_607A_0_Targetposition pshm->ECAT[0].IO[9].Data
#define Slave_1003_Diamond_E_1003_6071_0_Targettorque pshm->ECAT[0].IO[10].Data
#define Slave_1003_Diamond_E_1003_6060_0_Modesofoperation pshm->ECAT[0].IO[11].Data

// Slave_1004 [Diamond - E] Station Address-1004
#define Slave_1004_Diamond_E_1004_Index 3

// Inputs
#define Slave_1004_Diamond_E_1004_6041_0_Statusword pshm->ECAT[0].IO[4111].Data
#define Slave_1004_Diamond_E_1004_6064_0_Positionactualvalue pshm->ECAT[0].IO[4112].Data
#define Slave_1004_Diamond_E_1004_6077_0_Torqueactualvalue pshm->ECAT[0].IO[4113].Data
#define Slave_1004_Diamond_E_1004_6061_0_Modesofoperationdisplay pshm->ECAT[0].IO[4114].Data
#define Slave_1004_Diamond_E_1004_60FD_0_Digitalinputs pshm->ECAT[0].IO[4115].Data

// Outputs
#define Slave_1004_Diamond_E_1004_6040_0_Controlword pshm->ECAT[0].IO[12].Data
#define Slave_1004_Diamond_E_1004_607A_0_Targetposition pshm->ECAT[0].IO[13].Data
#define Slave_1004_Diamond_E_1004_6071_0_Targettorque pshm->ECAT[0].IO[14].Data
#define Slave_1004_Diamond_E_1004_6060_0_Modesofoperation pshm->ECAT[0].IO[15].Data

// Slave_1005 [Diamond - E] Station Address-1005
#define Slave_1005_Diamond_E_1005_Index 4

// Inputs
#define Slave_1005_Diamond_E_1005_6041_0_Statusword pshm->ECAT[0].IO[4116].Data
#define Slave_1005_Diamond_E_1005_6064_0_Positionactualvalue pshm->ECAT[0].IO[4117].Data
#define Slave_1005_Diamond_E_1005_6077_0_Torqueactualvalue pshm->ECAT[0].IO[4118].Data
#define Slave_1005_Diamond_E_1005_6061_0_Modesofoperationdisplay pshm->ECAT[0].IO[4119].Data
#define Slave_1005_Diamond_E_1005_60FD_0_Digitalinputs pshm->ECAT[0].IO[4120].Data

// Outputs
#define Slave_1005_Diamond_E_1005_6040_0_Controlword pshm->ECAT[0].IO[16].Data
#define Slave_1005_Diamond_E_1005_607A_0_Targetposition pshm->ECAT[0].IO[17].Data
#define Slave_1005_Diamond_E_1005_6071_0_Targettorque pshm->ECAT[0].IO[18].Data
#define Slave_1005_Diamond_E_1005_6060_0_Modesofoperation pshm->ECAT[0].IO[19].Data
